"""
SME Query Validator — Streamlit UI

Compare a self-service tool's SQL query against an SME's gold-standard query
using 3 evaluation tools with weighted scoring.

Run:  streamlit run app.py
"""
from __future__ import annotations

import json
import traceback
from pathlib import Path

import streamlit as st

from convert_db import create_sqlite_db, SQLITE_PATH
from providers import build_provider
from tools import run_full_comparison

# ── Page config ────────────────────────────────────────────────────────────

st.set_page_config(
    page_title="SME Query Validator",
    page_icon="🔍",
    layout="wide",
)

# ── Ensure SQLite DB exists ────────────────────────────────────────────────

if not SQLITE_PATH.exists():
    with st.spinner("Creating SQLite database from CSV data..."):
        create_sqlite_db()

# ── Header ─────────────────────────────────────────────────────────────────

st.title("SME Query Validator")
st.markdown(
    "Compare a SQL query generated by a self-service tool against "
    "an SME's gold-standard reference query. The system evaluates "
    "**Metric Identification**, **Query Formulation**, and **Result Agreement**."
)

st.divider()

# ── Business Query ─────────────────────────────────────────────────────────

st.subheader("Business Question")
business_query = st.text_area(
    "Paste the business question here",
    height=100,
    placeholder="e.g., What is the average turnaround time by platform and claim type?",
    key="business_query",
)

# ── SQL Queries ────────────────────────────────────────────────────────────

col_gen, col_sme = st.columns(2)

with col_gen:
    st.subheader("Generated SQL (Self-Service Tool)")
    generated_sql = st.text_area(
        "Paste the SQL generated by the self-service tool",
        height=250,
        placeholder="SELECT ...",
        key="generated_sql",
    )

with col_sme:
    st.subheader("Gold Standard SQL (SME Reference)")
    sme_sql = st.text_area(
        "Paste your gold-standard SQL query",
        height=250,
        placeholder="SELECT ...",
        key="sme_sql",
    )

st.divider()

# ── Compare Button ─────────────────────────────────────────────────────────

compare_clicked = st.button(
    "🔎 Compare Queries",
    type="primary",
    use_container_width=True,
)

if compare_clicked:
    # Validate inputs
    if not business_query.strip():
        st.error("Please enter a business question.")
        st.stop()
    if not generated_sql.strip():
        st.error("Please paste the generated SQL query.")
        st.stop()
    if not sme_sql.strip():
        st.error("Please paste the SME gold-standard SQL query.")
        st.stop()

    # Run comparison
    try:
        with st.spinner("Initializing LLM provider..."):
            provider = build_provider()

        with st.spinner("Running evaluation tools — this may take a minute..."):
            result = run_full_comparison(
                provider,
                business_query.strip(),
                generated_sql.strip(),
                sme_sql.strip(),
            )

        # ── Final Result Banner ────────────────────────────────────────
        st.divider()
        score_pct = result.final_weighted_score * 100

        if result.pass_fail == "PASS":
            st.success(
                f"✅ **PASS** — Final Weighted Score: **{score_pct:.1f}%**"
            )
        else:
            st.error(
                f"❌ **FAIL** — Final Weighted Score: **{score_pct:.1f}%**  "
                f"(Threshold: 70%)"
            )

        # ── Score Summary ──────────────────────────────────────────────
        st.subheader("Score Summary")
        sc1, sc2, sc3, sc_final = st.columns(4)
        with sc1:
            st.metric(
                "Tool 1: Metric ID",
                f"{result.tool1_score * 100:.1f}%",
                help="Weight: 40%",
            )
        with sc2:
            st.metric(
                "Tool 2: SQL Equiv.",
                f"{result.tool2_score * 100:.1f}%",
                help="Weight: 40%",
            )
        with sc3:
            st.metric(
                "Tool 3: Result Agree.",
                f"{result.tool3_score * 100:.1f}%",
                help="Weight: 20%",
            )
        with sc_final:
            st.metric(
                "Weighted Final",
                f"{score_pct:.1f}%",
            )

        st.markdown(
            f"**Calculation:** "
            f"({result.tool1_score:.2f} × 0.40) + "
            f"({result.tool2_score:.2f} × 0.40) + "
            f"({result.tool3_score:.2f} × 0.20) = "
            f"**{result.final_weighted_score:.4f}**"
        )

        # ── Detailed Results ───────────────────────────────────────────
        st.divider()
        st.subheader("Detailed Results")

        tab1, tab2, tab3 = st.tabs([
            "🎯 Tool 1: Metric Identification",
            "📐 Tool 2: Query Formulation",
            "🧪 Tool 3: Result Agreement",
        ])

        # ── Tab 1: Metric Identification ──
        with tab1:
            t1 = result.tool1_detail
            if t1:
                st.markdown(f"**Score:** {t1.metric_match_score * 100:.1f}% (Weight: 40%)")
                st.markdown(f"**Reasoning:** {t1.reasoning}")

                col_a, col_b = st.columns(2)
                with col_a:
                    st.markdown(f"**Total metrics in SME query:** {t1.total_metrics_in_sme}")
                    st.markdown(f"**Correctly identified:** {t1.correct_count}")
                with col_b:
                    if t1.grain_analysis:
                        st.markdown("**Grain Analysis:**")
                        st.json(t1.grain_analysis)

                if t1.correct_metric_fields:
                    st.markdown("**Metric Mappings:**")
                    st.json(t1.correct_metric_fields)
            else:
                st.info("No detailed results available.")

        # ── Tab 2: Query Formulation ──
        with tab2:
            t2 = result.tool2_detail
            if t2:
                st.markdown(f"**SQL Equivalence Score:** {t2.sql_equivalence_score * 100:.1f}% (Weight: 40%)")
                st.markdown(f"**Reasoning:** {t2.reasoning}")

                st.markdown("**Component Jaccard Similarities:**")
                comp_data = {
                    "Component": [
                        "Tables/Joins",
                        "Filters & Time Windows",
                        "GROUP BY Grain",
                        "Aggregations",
                        "SELECT Columns",
                    ],
                    "Jaccard Score": [
                        f"{t2.table_similarity:.2f}",
                        f"{t2.filter_similarity:.2f}",
                        f"{t2.groupby_similarity:.2f}",
                        f"{t2.aggregation_similarity:.2f}",
                        f"{t2.select_similarity:.2f}",
                    ],
                    "Weight": ["20%"] * 5,
                    "Weighted": [
                        f"{t2.table_similarity * 0.20:.4f}",
                        f"{t2.filter_similarity * 0.20:.4f}",
                        f"{t2.groupby_similarity * 0.20:.4f}",
                        f"{t2.aggregation_similarity * 0.20:.4f}",
                        f"{t2.select_similarity * 0.20:.4f}",
                    ],
                }
                st.table(comp_data)

                if t2.component_details:
                    with st.expander("Full Component Details (JSON)"):
                        st.json(t2.component_details)
            else:
                st.info("No detailed results available.")

        # ── Tab 3: Result Agreement ──
        with tab3:
            t3 = result.tool3_detail
            if t3:
                st.markdown(f"**Agreement Score:** {t3.agreement_score * 100:.1f}% (Weight: 20%)")
                st.markdown(f"**Result Type:** {t3.result_type}")
                st.markdown(f"**Method Used:** {t3.method_used}")
                st.markdown(f"**Reasoning:** {t3.reasoning}")

                if t3.execution_error:
                    st.warning(f"**Execution Error:** {t3.execution_error}")

                res_gen, res_gold = st.columns(2)
                with res_gen:
                    st.markdown("**Generated SQL Results:**")
                    if isinstance(t3.generated_result, list) and t3.generated_result:
                        st.dataframe(t3.generated_result, use_container_width=True)
                    elif t3.generated_result:
                        st.json(t3.generated_result)
                    else:
                        st.info("No results (query error or empty)")
                with res_gold:
                    st.markdown("**Gold Standard SQL Results:**")
                    if isinstance(t3.gold_result, list) and t3.gold_result:
                        st.dataframe(t3.gold_result, use_container_width=True)
                    elif t3.gold_result:
                        st.json(t3.gold_result)
                    else:
                        st.info("No results (query error or empty)")
            else:
                st.info("No detailed results available.")

    except Exception as e:
        st.error(f"An error occurred: {e}")
        with st.expander("Full traceback"):
            st.code(traceback.format_exc())
